### ISSUE TITLE
time:create does not work for "day" input

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#12]
time:create will not create a logotime of type "day", e.g.:
let t-day time:create "01-02"

(on the other hand, create-with-format *does* work for day input types.)

**Comment by charlesres** [comment]
Hi @SFRailsback, I was able to reproduce the issue and added a fix in the latest commit.
With the issue with day, I will leave this issue open for time:create-with-format, since it experiences a similar issue with day. Thanks for submitting.
