### ISSUE TITLE
Inconsistent rounding in time:plus for "date" format logotimes

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#13]
When time:plus is used to modify a *date* (not datetime) logotime, by adding a non-integer number of days (weeks, seconds, etc.), it rounds that non-integer down to the next-lowest integer, whether or not the number is negative. Example:
time:plus 23.372 "days" adds 23 days to the date, while
time:plus -23.372 "days" subtracts 24 days from the date.

This seems likely to cause confusion; should we instead simply always truncate the input to an integer, or round it to the nearest integer?
In any case, the documentation for time:plus needs to explain this case.

**Comment by charlesres** [comment]
@SFRailsback Thanks for reporting this issue. This issue is related to unsupported units and how operations are applied to day/date, which are meant to convert to datetime and back. I ran some tests against time-v1.3 and found this was changed with the source update. I'll take a closer look soon.

**Comment by charlesres** [comment]
@SFRailsback. The issue you were having was due to the truncation of seconds. Before, values would be converted to seconds, which could not be truncated. time:plus, now, converts values to days and truncates the value, following the initial implementation.
