### ISSUE TITLE
Documentation: sub-millisecond fractions of a second are truncated

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#3]
Minor documentation item: at "Time extension has millisecond resolution", add something like: "If a Logotime is created with more than 3 decimal places in the seconds field, those decimal places smaller than 1 millisecond are truncated."

**Comment by charlesres** [comment]
Hi @SFRailsback. Thanks for submitting an issue. I'll add that into the doc. There were some issues with floating point values in the parser, so there is now support for truncating to the third decimal place.
