### ISSUE TITLE
Documentation: Behavior of "difference-between" for months, years

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#4]
Augment this sentence in the documentation for time:is-between: "Note that if the period type is YEAR or MONTH, then the reported value will be a whole number based soley on the month and year components of the LogoTimes." Add something like:
"For period type of "MONTH", is-between calculates the number of months between dates as the number of days there are between logotime1 and logotime2 that have the same day value as logotime1. For example, if logotime1 is 2000-01-02 then is-between reports 0 months for logotime2 = 2000-02-01 and 1 month for 2000-02-02. However, the value reported is never greater than 11 or less than -11; it reverts to zero when logotime2 reaches one year from logotime1 and then is 1 when logotime2 is 13 months after logotime1, etc. For "YEAR", is-between reports the integer number of days there are between logotime1 and logotime2 that have the same month and day of logotime1:  if logotime1 is 2000-01-02 then is-between reports 0 years for logotime2 = 2001-01-01, 1 year for 2000-01-02, and 5 years for 2005-04-28. The total number of months between two dates can therefore be calculated as 12 times the value of of is-between in years plus the value of is-between in months."

**Comment by charlesres** [comment]
@SFRailsback. Thanks for taking a look at "difference-between" behavior. I'll add those notes in the next batch of commits.

**Comment by charlesres** [comment]
Added documentation on difference-between for month and year. This should include leap years, as well.
