### ISSUE TITLE
Documentation: time:get does not round to nearest value.

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#5]
Add to documentation for time:get:
Be aware that time:get returns the date-time field value specified by the period type; it does *not* round its result to the nearest integer. For example, for the time 2000-01-02 03:44:55.978 the value of time:get "hour" is 3; of time:get "minute" is 44; of time:get "second" is 55, not 56.

**Comment by charlesres** [comment]
@SFRailsback, thanks for submitting. I'll take a look at updating the docs for time:get. For rounding seconds, seconds and milliseconds are represented 'as is' to avoid confusion with the datetime output.
