### ISSUE TITLE
create-with-format does not catch illegal dates

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#8]
Currently, time:create-with-format does not throw an exception when given an impossible month-date combination (such as June 31, February 29). Instead, it changes the day to the last feasible day. Examples:

This string: 2/30/2724   1:4:39.677 becomes this date: 2724-02-29 01:04:39.677
                  2/30/1029 7:48:13.715 becomes                 1029-02-28 07:48:13.715

In contrast, time:create does throw an exception in such cases.

**Comment by charlesres** [comment]
@SFRailsback I agree, both time:create-with-format and time:create should throw an exception for invalid dates. Thanks for reporting this issue.

**Comment by SFRailsback** [comment]
This problem occurs with logotimes created as dates as well as datetimes.
